### ISSUE TITLE
This package seems to be dead

### ISSUE THREAD

**Issue by justintoth** [wrathyz/react-native-immersive-mode#10]
I was running into issues building for Android after upgrading to RN 0.72.1, due to this package. It was saying the CompileSdk version had to be upgraded to version 30 or greater. Seeming that there have been no updates to this package in 2+ years, I wanted to share with others that a more up to date alternative that works with the latest version of RN is [https://github.com/kadiraydinli/react-native-system-navigation-bar](https://github.com/kadiraydinli/react-native-system-navigation-bar).

**Comment by wrathyz** [comment]
It's still work for previous RN version, thank for report it not work for new RN, i"ll will upgrade.
