### ISSUE TITLE
RNImmersiveMode is not properly linked

### ISSUE THREAD

**Issue by maufernandezdev** [wrathyz/react-native-immersive-mode#12]
I have the following message when i try to use _ImmersiveMode.setBarStyle('Dark');_ . I read in index.js file that RNImmersiveMode is declared there. Are there any solution on my side? ty!

**Comment by wrathyz** [comment]
Can you give more information about react native version, device, lib version. or code did test it.

**Comment by ManuSense** [comment]
I have the same problem: _Error: RNImmersiveMode is not properly linked_. Here my dependencies:
`{
  "name": "i-fabric",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@tanstack/react-query": "^5.17.15",
    "axios": "^1.6.5",
    "expo": "~49.0.15",
    "expo-font": "~11.4.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-dotenv": "^3.4.9",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-immersive-mode": "^2.0.1",
    "react-native-reanimated": "~3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`

**Comment by wrathyz** [comment]
@ManuSense Sorry, not supported for Expo.
