### ISSUE TITLE
Auto-Hide Navigation Bar Again After User Swipe in Immersive Mode

### ISSUE THREAD

**Issue by patrickspafford** [wrathyz/react-native-immersive-mode#7]
Hi,

I would like to auto-hide the navigation bar after the user swipes up from the bottom and waits a few seconds while in immersive mode. It seems that in this scenario, calling setBarMode does not change the UI and the visibility listener is (correctly) not triggered. Any idea what might be going on here? I tried setting a delay on the JS side before attempting to hide the navigation bar again, but to no effect.

Current process:

app launch -> setBarMode('Bottom') -> hides navigation bar -> swipe up -> show navigation bar -> wait a few seconds -> setBarMode('Bottom') -> no effect

Desired effect:
app launch -> setBarMode('Bottom') -> hides navigation bar -> swipe up -> show navigation bar -> wait a few seconds -> setBarMode('Bottom') -> hides navigation bar again

Thanks!

**Comment by mlhtnc** [comment]
```typescript
useEffect(() => {
  const onAppStateChange = (state: AppStateStatus) => {
    if (state === 'active') {
      ImmersiveMode.setBarMode('Normal');
      ImmersiveMode.fullLayout(false);
      setTimeout(() => {
        ImmersiveMode.setBarMode('FullSticky');
        ImmersiveMode.fullLayout(true);
      }, 0);
    }
  };

  const sub = AppState.addEventListener('change', onAppStateChange);

  return () => {
    sub.remove();
  };
}, []);
```

@patrickspafford's suggestion above helps my problem also. Immersive mode was resetting by android system when app is in background (by pressing home button etc.). So after returning back to app, status bar and navigation bar is visible again, this code above fixes the issue.
