### ISSUE TITLE
is there a way to get the current mode the device is using ?

### ISSUE THREAD

**Issue by a-eid** [wrathyz/react-native-immersive-mode#8]
Thank you for the library, 

I was wondering if there is way to know if the user is using immersive mode when launching the app.

something like 

```ts
import immersiveMode from 'react-native-immersive-mode' 

immersiveMode.currentMode 

immersiveMode.getCurrentMode()

```

**Comment by a-eid** [comment]
my use case:

I want to apply some extra `safe area insets` to avoid the area where the use drags to dismiss, kinda like ios home bottom insets.

**Comment by wrathyz** [comment]
@a-eid Usually launching app the mode should be unset means it's Normal except you set it by another library.

however, I can add that method but result will incorrect in some case eg. if you use `StatusBar.setHidden()` it will be set at android system UI then if you get current mode from this library it will be incorrect.

**Comment by a-eid** [comment]
I probably got confused between immersive mode and the android option to hide the navigation bar. 

Is there a way to get the visibility status for the navigation bar and probably the status bar as well ?

**Comment by wrathyz** [comment]
@a-eid Did you try this [`addEventListener` ](https://github.com/wrathyz/react-native-immersive-mode#addeventlistener), it subscribe visibility of navigation bar and status bar.

**Comment by a-eid** [comment]
it doesn't seem to be working, but looking at the lib code, I think I can submit a PR to add this feature.

will try it as soon as I can.

thank you.
