### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by kalvin1322** [wrathyz/react-native-immersive-mode#9]
i followed all the configuration steps but when i create the apk and try to install it on the phone the app crashes... to be safe i deleted the code for the full screen mode and i recreated the apk, this time without the libraries and configurations for full screen mode the app didn't crash. I also tried to create an apk where all the libraries/steps for full-screen mode I had done but I never called the ImmersiveMode.fullLayout(true) function in app.js and the app crashed anyway, as a consequence I guessed that the problem was in the configuration steps of the files in the android folder. also using react-native with expo my MainApplication.java file was slightly different. I'm a beginner, I've never programmed in java and I can't figure out which step I went wrong.

**Comment by wrathyz** [comment]
this lib is not support for expo.
